# Generated by Django 4.0.6 on 2022-07-25 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('mailling', models.BooleanField(default=True)),
                ('planning', models.BooleanField(default=True)),
                ('promotion', models.BooleanField(default=True)),
                ('smoothie', models.BooleanField(default=False)),
                ('distributer', models.BooleanField(default=False)),
                ('spa', models.BooleanField(default=False)),
                ('statistic', models.BooleanField(default=False)),
                ('coaching', models.BooleanField(default=True)),
                ('shower', models.BooleanField(default=True)),
                ('entretien', models.BooleanField(default=False)),
                ('proteine', models.BooleanField(default=True)),
                ('massage', models.BooleanField(default=False)),
                ('evenement', models.BooleanField(default=False)),
                ('concours', models.BooleanField(default=False)),
                ('nettoyage', models.BooleanField(default=False)),
                ('assurance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to='icons/structures')),
                ('franchise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='franchise.franchise')),
                ('permissions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.permission')),
            ],
        ),
        migrations.CreateModel(
            name='StructurePerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.permission')),
                ('structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structure')),
            ],
        ),
    ]
