# Generated by Django 4.0.6 on 2022-08-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_structure_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='slug',
            field=models.SlugField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
