# Generated by Django 4.0.6 on 2022-08-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_permission_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='assurance',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='coaching',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='concours',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='distributer',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='entretien',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='evenement',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='mailling',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='massage',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='nettoyage',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='planning',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='proteine',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='shower',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='smoothie',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='spa',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='statistic',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='permissions',
        ),
        migrations.AddField(
            model_name='permission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='structureperm',
            name='permission',
        ),
        migrations.AddField(
            model_name='structureperm',
            name='permission',
            field=models.ManyToManyField(blank=True, null=True, to='structure.permission'),
        ),
    ]
