# Generated by Django 4.0.6 on 2022-08-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_structureperm_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='icon',
            field=models.ImageField(null=True, upload_to='icons/permissions'),
        ),
    ]
