# Generated by Django 4.0.6 on 2022-08-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_permission_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/permissions'),
        ),
    ]
