# Generated by Django 4.0.6 on 2022-08-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_structure_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='permission',
            field=models.ManyToManyField(blank=True, null=True, to='structure.permission'),
        ),
        migrations.DeleteModel(
            name='StructurePerm',
        ),
    ]
