# Generated by Django 4.0.6 on 2022-08-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
        ('structure', '0009_structure_permission_delete_structureperm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AlterField(
            model_name='structure',
            name='permission',
            field=models.ManyToManyField(blank=True, null=True, to='permission.permission'),
        ),
    ]
