# Generated by Django 4.0.6 on 2022-08-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_delete_permission_alter_structure_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icons/structures'),
        ),
    ]
