# Generated by Django 4.0.6 on 2022-08-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0011_alter_structure_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='image',
            field=models.ImageField(blank=True, default='icons/structures/1.png', null=True, upload_to='icons/structures'),
        ),
    ]
