# Generated by Django 4.0.6 on 2022-08-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('staff', 'staff'), ('franchise manager', 'franchise manager'), ('structure manager', 'structure manager'), ('employee', 'employee')], max_length=100, null=True),
        ),
    ]
