# Generated by Django 4.0.6 on 2022-08-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/permissions')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
