# Generated by Django 4.0.6 on 2022-07-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_franchise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='slug',
            field=models.SlugField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
