# Generated by Django 4.0.6 on 2022-08-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0003_franchise_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='franchise',
            old_name='user',
            new_name='manager',
        ),
    ]
